#!/bin/bash
CODEDIR="$PWD"
SERVICEDIR="$(dirname "$0")"

TARBALL=http://dist.neo4j.org/neo4j-community-1.5.M02-unix.tar.gz
INSTALL_DIRECTORY="$HOME/neo4j-community-1.5.M02"

cd
if [ -d "$INSTALL_DIRECTORY" ]
then
    echo "Neo4j found. Skipping install phase."
else
    echo "Neo4j not found. Installing it..."
    mkdir -p $INSTALL_DIRECTORY
    curl "$TARBALL" | tar -zxf- --strip-components=1 -C "$INSTALL_DIRECTORY"
fi

cat > ~/profile << EOF
INSTALL_DIRECTORY="$INSTALL_DIRECTORY"
EOF
